/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RpZf29wy3N0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectGroup,
  SelectItem,
} from "@/components/ui/select";

import Image from "next/image";
import { OPTIONS } from "@/constants/dropdown";
import { useState } from "react";

export function Dropdown({ value, setItemVal }) {
  return (
    <div className="flex flex-col items-start gap-2">
      <label htmlFor="dropdown" className="text-sm font-medium text-gray-700">
        Select an option
      </label>
      <div className="relative w-full">
        <Select
          id="dropdown"
          className="w-full"
          onValueChange={(e) => {
            setItemVal(e);
          }}
        >
          <SelectTrigger
            className="w-full bg-white/20 border-gray"
            value={value}
          >
            <SelectValue placeholder="" />
          </SelectTrigger>
          <SelectContent className="border-gray bg-white">
            <SelectGroup>
              {OPTIONS.map((option, index) => {
                return (
                  <SelectItem
                    key={index}
                    value={option.value}
                    className={`hover:bg-gray/20`}
                  >
                    <div className="flex flex-row items-center gap-2">
                      {option.icon}
                      <h3>{option.label}</h3>
                    </div>
                  </SelectItem>
                );
              })}
            </SelectGroup>
          </SelectContent>
        </Select>
      </div>
    </div>
  );
}
